// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bsxtcihytnupijzegrku.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJzeHRjaWh5dG51cGlqemVncmt1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5MzM5OTIsImV4cCI6MjA2NDUwOTk5Mn0.yF7ZLGhbzLlfO9QZ_c-3glHiZEWKYpVC2uftWsW28K4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);